### ISSUE TITLE
ビルダーが無限にリロードを繰り返す場合がある

### ISSUE THREAD

**Issue by solkanet** [RAPT21/bro3-tools#11]
以前からたまに起きていた不具合の再現性が確認できたので報告させていただきます。
・兵士の研究中に施設の建設・強化を行う
・当該拠点をブラウザで表示している
上記の2点が重なった場合INTERVALに指定された時間ごとにリロードを繰り返してしまうというものです。
ブラウザで別タブを表示している間は発生しないため、環境による差なのかもしれません。
また、この不具合発生時に見られる現象として建設時間・研究時間・内政スキル時間・武闘祭の体力回復時間などといった表示時間が入れ替わるというものも確認できました。
一例です　https://gyazo.com/55a924589d6c94e1bce9c7654cfddbcf
ご確認いただければと思います。
Firefox56.0 + Greasemonkey 3.17 にて確認しております。

**Comment by RAPT21** [comment]
@solkanet
建築や造兵等の時間が内政スキルの残り時間またはスキル回復時間などになってしまう問題については以前から認識しています。

ビルダーを有効にすると高い確率で発生しますが、一切ツールを使っていない状態でも発生したことがあります。
そのため、事象としては運営側のタイマーバグである認識です。

タイマーバグ発生時、画面を読み込み直すことで解消することがあるため、
タイマーバグ検出時にリロードする対策が入っています。

最近はそれでも解消できないことが多い場合、無駄なリロードを減らすため、リロードまでの発動時間を長めにするといいかも
しれません。
ソースの2100行付近「建築時間がバグ」で検索し、そこのタイムアウト時間を延ばしてみてください。

**Comment by solkanet** [comment]
@RAPT21 
なるほど、運営側のバグの可能性でしたか。
教えていただいたタイムアウト時間を延長したところ、無限リロードは回避できました。
お手数をおかけしました。
