### ISSUE TITLE
突然拠点情報が取得されなくなる

### ISSUE THREAD

**Issue by Raiming** [RAPT21/bro3-tools#12]
最初は使えていたのですが、何かのタイミングで拠点情報が取得されなくなりました。
次回：3/05・・・のように何かのスケジュールのみが巡回中などのボタンの下に緑色で表示されるのですが、その時刻になっても特に何も動作せず、再度新たなスケジュールが表示されるのみです。そのため、拠点ごとの設定などが一切できず、ビルダーが動作しない状態に陥ってしまいます。

再インストールや再起動等行いましたが、改善しませんでした。
(再インストールすると、一瞬拠点情報を取得して拠点ごとの設定画面を開くことができるのですが、すぐに先ほどの状態に戻ってしまいます）

バグなのか、使い方が悪いのか分かりませんが、よろしくお願いいたします。

使用環境:FireFox, Greasemonkey最新版

**Comment by Raiming** [comment]
https://gyazo.com/37cef537e1edcc732ec99cce3259220f

**Comment by solkanet** [comment]
建設完了などのログが溜まっていませんか？
確認済ボタン、閉じるボタンの順に押して、再度設定画面を開いてみて下さい。
ログが原因なら解消するのではないかと思います。

**Comment by RAPT21** [comment]
@Raiming
拠点情報が取得できない場合、大抵の場合は Beyond など他のツールをすべて無効にしてからプロフィール画面を表示することで拠点情報が読み込めるようになると思います。
ほかのツールが動いていないか一度確認してみてください。

「次回: 」のあとに続くのは最も近い何かの完了時刻です。

期が変わった場合は、以前の期の情報が残っているだけの場合があります。
その場合は最新のデータが取れたときに更新されるのであまり気にしなくていいと思います。
