### ISSUE TITLE
ヤバゲが・・・

### ISSUE THREAD

**Issue by kenichi90kg** [RAPT21/bro3-tools#13]
http://yahoo-mbga.jpでまーったく動かなくなりました。
動かないどころか表示すらされないものも・・・( ﾉД`)ｼｸｼｸ…

どないかして頂けませんか？

**Comment by RAPT21** [comment]
@kenichi90kg 
昨日のメンテ以降、一部のブラウザで動作基盤が変更されたようです。

Firefox ESR 52.9.0 では以前のまま: `http://*.3gokushi.jp/` ドメインで動作。
Firefox 74.0 と Google Chrome 80.0 では新基盤: `http://fc9bb5776358681100f8c27fb8c69f3c21ced89a.app.mbga-platform.jp/` ドメイン経由で動作。

現時点では回避方法が見つかっていません。
とりあえずは古い Firefox を使うしかなさそうです。

**Comment by RAPT21** [comment]
とりあえず、UserAgent を Android にしてみたら動いた。

**Comment by RAPT21** [comment]
Google Chrome 80.0 で、UserAgent を Android に設定してみたら動いた。
サーバー側で何か振り分けしてるっぽいな。

**Comment by kenichi90kg** [comment]
Firefox ESR 52.9.0でもダメでした(´；ω；`)ｳｩｩ

**Comment by RAPT21** [comment]
@kenichi90kg 
上記 User Agent を変更する方法は試されたでしょうか？
設定手順については下記記事をご参考ください。
[ブラウザーごとの User Agent 設定方法](https://github.com/RAPT21/bro3-tools/blob/master/how_to_change_user_agent.md)

**Comment by kenichi90kg** [comment]
変更すると下記のような画面になりログインも出来なくなりました。
https://gyazo.com/a16c84bb8d35de5b3dee24a177249125

**Comment by RAPT21** [comment]
@ kenichi90kg
4/7 のメンテ以降？で UserAgent を変更しても以前のとおり使えるようになったようです。

**Comment by kenichi90kg** [comment]
できました～＼(^o^)／
ありがとうございます＾＾

**Comment by RAPT21** [comment]
解決したとのことなのでクローズします。
