### ISSUE TITLE
大倉庫二階　への対応のお願い

### ISSUE THREAD

**Issue by solkanet** [RAPT21/bro3-tools#15]
いつもお世話になっております。
大倉庫二階　が実装され、これも自動レベルアップできれば嬉しいのですがいかがでしょうか。
自力で355行目辺りの最大レベルを21、6709行辺りの必要資源などを追加して
大倉庫Lv.20　を　大倉庫二階Lv.1　にすることはできたのですが、それ以降は無理でした・・・
参考までに必要資源などを記載しておきます。
{wood: 153600, stone: 184320, iron: 153600, food: 122880, time: 39840}, //2F-lv1
{wood: 76800, stone: 92160, iron: 76800, food: 61440, time: 39840}, //2F-lv2
{wood: 76800, stone: 92160, iron: 76800, food: 61440, time: 39840}, //2F-lv3
{wood: 76800, stone: 92160, iron: 76800, food: 61440, time: 39840}, //2F-lv4
{wood: 76800, stone: 92160, iron: 76800, food: 61440, time: 39840}, //2F-lv5

**Comment by RAPT21** [comment]
@solkanet
お待たせしました。ようやく少し時間が取れたので対応しました。
2020/04/21 版にてお試しください。

設定画面では、大倉庫欄を使い、21-25 をセットすると、大倉庫二階 LV1-5 に対応します。

※「大倉庫二階の設計図」所持チェックはしていませんので建設できない場合はクエクリ確認してください。

**Comment by solkanet** [comment]
お返事大変遅くなりました。
ご対応いただきありがとうございました。
今後ともよろしくお願いします。
