### ISSUE TITLE
ブラ三で一括デッキアップする機能を作成して頂けないでしょうか・・・

### ISSUE THREAD

**Issue by hataboo0109** [RAPT21/bro3-tools#16]
不躾な要望で大変申し訳ありません。

全軍攻令武将，全軍速令武将，全軍王威令武将，防御武将，加護スキル武将，軍極武将，督戦武将など、指定拠点に複数カードをデッキアップする局面が多々あります。これを一括でデッキアップさせる機能があれば大変便利であると思い、是非実現していただきたい機能としてお願いしたいと思います。お忙しい事とは思いますが、何卒ご検討お願い致します。

**Comment by RAPT21** [comment]
@hataboo0109 
ちょうど、10/22 のアップデートにて運営実装されたようなのでクローズします。
