### ISSUE TITLE
自動デュエル

### ISSUE THREAD

**Issue by hataboo0109** [RAPT21/bro3-tools#28]
bro3_auto_daily_quest(version 2020.12.06)で、自動デュエルが動作しない鯖があります。お手数ですがご確認をお願います。

自動デュエルが動作しない鯖ですが、4コスト武将を5体セットしています。6体20コストでセットできるところ、5体20コストでデッキセットしていることが原因なのでしょうか？もしそうでしたらお手数ですが修正をお願い致します。

**Comment by RAPT21** [comment]
@hataboo0109 
自動デュエルはその仕様上、６枚目にカードセットされている必要があります。
５枚であっても、６枚目にカードがセットされていれば動作すると思います。

**Comment by hataboo0109** [comment]
６枚目にカードをセットすることで、
無事自動デュエルが動作しました。
ありがとうございました。
