### ISSUE TITLE
2022.6.30のメンテ後から軍備貯蓄が動きません

### ISSUE THREAD

**Issue by hataboo0109** [RAPT21/bro3-tools#31]
いつも大変お世話になっております。

6022.6.30メンテ後から軍備貯蓄が動きません。
メンテ前までは動いていました。
設定も触っていません。
お手数ですが調査をお願いします。

**Comment by RAPT21** [comment]
@hataboo0109 
修正しました。
61d390b4822788c2f1195feb497044a8f6886dca
