### ISSUE TITLE
Tampermonkyを更新したら…

### ISSUE THREAD

**Issue by ZX14R** [RAPT21/bro3-tools#33]
4.18に上げたらオートビルダーが表示されなくなりました。
軍費と合わせて対応して頂けたら幸いです
Chrome 106.0.5249.103 使用です

**Comment by kisara-icy** [comment]
window.chromeが期待した値では無くなっている状態？で、こちらのcloadDataが正しく動いてないようです。

```javascript
function cloadData(key, value, local, ev)
{
	if( local ) key = location.hostname + key  + PGNAME;
	var ret = GM_getValue(key, value);

	if (window.chrome) { // 2015.05.23
		return ev ? eval(eval('ret='+ret)) : ret;
	} else {
		return ev ? eval('ret='+ret) : ret;
	}
}
```

やっつけで、Chrome判定部分を変えてみると一応動きましたが、これで意図した振り分けがされるか私の方では判断つきません。

```javascript
function cloadData(key, value, local, ev)
{
	if( local ) key = location.hostname + key  + PGNAME;
	var ret = GM_getValue(key, value);

	var agent = window.navigator.userAgent.toLowerCase();
	if (agent.indexOf("chrome") != -1) {
		return ev ? eval(eval('ret='+ret)) : ret;
	} else {
		return ev ? eval('ret='+ret) : ret;
	}
}
```

もし、これ以前に拠点名のところの[自動建設]が表示されてなかったり、AutoBuilderの拠点一覧の表示がされないなど、一切動いてないようでしたら、ブラウザやPCの再起動、tampermonkeyの再インストールなどを試してみてください。
私も最初全然動かなかったのでtampermonkey自体をアンインストールしてから再インストールすると動きました。
再インストールの場合、設定が全部リセットされるので注意です。

**Comment by RAPT21** [comment]
@ZX14R @kisara-icy 
ご報告および修正スニペットありがとうございます。
参考にさせていただきます。

**Comment by RAPT21** [comment]
@ZX14R @kisara-icy 
修正版を公開しました。
61d390b4822788c2f1195feb497044a8f6886dca
