### ISSUE TITLE
回復時間検索・一括デッキアップのバグ修正について

### ISSUE THREAD

**Issue by pla2999** [RAPT21/bro3-tools#35]
お世話になっております。
[beyond]の以下のバグを修正しましたが、repositoryにmergeしていただくことは可能でしょうか？
可能であればコードを送らせていただきます。

1．回復時間検索
     検索結果の表示で、武将名が勢力(魏・呉・蜀）になっている
     ソートがおかしい
     付加機能として回復予定時間に残り時間(あと何分)を追加
     残る不具合として、覇武将のスキル5つ目に未対応

2. 一括デッキセット
     主に警護デッキの不具合対応(警護デッキに乗らない、コスト計算がおかしいなど)
     検索結果の表示部分削除
     
以上よろしくお願いします。

**Comment by RAPT21** [comment]
@pla2999 
ありがとうございます。
私が普段使わない機能はどうしても後回しになってしまうので助かります。
PR作成いただければ確認させていただきます。 🙇

**Comment by pla2999** [comment]
PR発行しましたので、よろしくお願いします。
