### ISSUE TITLE
作成中兵士数

### ISSUE THREAD

**Issue by solkanet** [RAPT21/bro3-tools#6]
ビルダーにおいて先のメンテから作成中の兵士数が正しく取得できなくなっているようです。

**Comment by RAPT21** [comment]
@solkanet 報告ありがとうございます。
2020.02.10版で対応してみました。

動作確認したところ、受けている援軍の兵数もカウント対象になるのですが、もとからそうなっていたかご存知でしょうか。

**Comment by solkanet** [comment]
@RAPT21 ご対応ありがとうございます。
確認してみましたところ、私の意図したところとは別の場所の修正をしていただいたようです。
今回の作成中の兵士数というのは
https://gyazo.com/95758e8867343c4110aef45509b0fd4a
の画面にある
02/11 02:30:02 (あと0:11:05) 練兵所:剣兵(1 / 毎時)
02/11 02:20:20 (あと0:01:23) 練兵所:剣兵(|)
の部分です。
var mSolNum = あたりの取得内容が変わってしまったのかと予想はしているのですが、技術も知識もないので・・・
お手数ですがもう一度ご確認いただければと思います。
確認はクローム80.0.3987.87　＋　Tampermonkey4.9にて行いました。

援軍の兵数もカウントの対象になる、という件についてですが自動造兵のことでしょうか？
そうであれば私自身が自動造兵を使用していなかったため、残念ながら不明です。
同盟内などでも使っていた人がいないようで不明です。
お力になれず申し訳ありません。

**Comment by ZX14R** [comment]
巡回、建設、市場変換等全く動作しませんが私だけ？
相変わらずhttpsの記述がありませんが、私の環境が邪魔をしてる？

**Comment by solkanet** [comment]
必要箇所のhttpをhttpsに変更すれば巡回、建設、市場変換等すべて機能しています。
ご自分でhttpをhttpsに書き換えられてはいかがですか？

**Comment by ZX14R** [comment]
スクリプト内全ての記述においてでしょうか？
今までは「// @include		https://*.3gokushi.jp/*」を書き足すだけで動作していました。

**Comment by solkanet** [comment]
http://SITE/facility/ のようなブラ三内を示す箇所はすべて変更です。
そのほかのサイトを示している箇所は不具合のない限り触らなくて良いと思います。

**Comment by RAPT21** [comment]
@solkanet なるほど、ビルダー上のログ表示の方だったんですね。確認いたします。

@ZX14R ビルダーの https 対応は本 issue とは直接関連がないので、次回からは新規 issue を立ててほしいです。

**Comment by solkanet** [comment]
@RAPT21 お手数をおかけしますが、お願いします。
GitHubは初心者なものでissue立てなどよくわかっておらず失礼しました。

**Comment by RAPT21** [comment]
@solkanet いえ、 solkanet さんは問題ありません。
ちょっと作業時間が取れていないですが、またあとで確認いたします。

**Comment by RAPT21** [comment]
@solkanet 2020/02/20 版にて修正いたしました。ご確認をお願い致します。

**Comment by solkanet** [comment]
ご対応いただきありがとうございます。
クローム80.0 + Tampermonkey4.9
Firefox 56.0 + Greasemonkey 3.17
の二つにおいて正常動作を確認いたしました。

ブラ三も長くなりツールを公開される方も減ってしまった中、更新を続けていただいて非常に助かっております。
今後ともよろしくお願いいたします。
大変恐縮なのですが、可能であれば私のページにて公開している右クリックツールの面倒を見ていただけないでしょうか・・・。
